name: Code Warden Requirements Analyzer
description: The official codewarden.ai GitHub action
author: codewarden.ai

branding:
  color: 'blue'
  icon: 'crosshair'

inputs:
  github-token:
    description: 'GitHub token'
    required: true
  jira-url:
    description: 'Jira URL'
    required: true
  jira-user:
    description: 'Jira username'
    required: true
  jira-password:
    description: 'Jira password'
    required: true
  jira-cloud-edition:
    description: 'Specify if you are using Jira Cloud edition'
    required: false
    default: 'false'
  comment-language:
    description: 'The language you want to Analysis to appear in'
    required: false
    default: 'English'   

runs:
  using: 'node16'
  main: 'codewarden.js'

